// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwEV8kfBMVX4wVia4eUq4fH2O-Zw_b_1w',
    appId: '1:511467920913:web:b580547c0c9d20002e9bb0',
    messagingSenderId: '511467920913',
    projectId: 'my-styfit',
    authDomain: 'my-styfit.firebaseapp.com',
    storageBucket: 'my-styfit.firebasestorage.app',
    measurementId: 'G-8REKQVVRXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIHlCKysQStCFHqIkjzMjKFK8vNKJV8RE',
    appId: '1:511467920913:android:6699586b3d5335312e9bb0',
    messagingSenderId: '511467920913',
    projectId: 'my-styfit',
    storageBucket: 'my-styfit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-7_0jsO3qJB1I1SwJWv1ss7p9iRxUyIY',
    appId: '1:511467920913:ios:a081941a5612ba672e9bb0',
    messagingSenderId: '511467920913',
    projectId: 'my-styfit',
    storageBucket: 'my-styfit.firebasestorage.app',
    iosBundleId: 'com.example.myWebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-7_0jsO3qJB1I1SwJWv1ss7p9iRxUyIY',
    appId: '1:511467920913:ios:a081941a5612ba672e9bb0',
    messagingSenderId: '511467920913',
    projectId: 'my-styfit',
    storageBucket: 'my-styfit.firebasestorage.app',
    iosBundleId: 'com.example.myWebsite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwEV8kfBMVX4wVia4eUq4fH2O-Zw_b_1w',
    appId: '1:511467920913:web:70478334eeb38abb2e9bb0',
    messagingSenderId: '511467920913',
    projectId: 'my-styfit',
    authDomain: 'my-styfit.firebaseapp.com',
    storageBucket: 'my-styfit.firebasestorage.app',
    measurementId: 'G-EHVFRNJ954',
  );

}